server.port: ${port:8031}
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
logging.level.com.netflix.eureka: false
logging.level.com.netflix.eureka.discovery: false
available.terminals: ${available.terminal.ids:1001,1002,1003,1004,1005}
terminal.processing.time.seconds: ${terminal.processing.time:1}
terminal.available.period.seconds: ${terminal.available.time:4}